#!/usr/local/bin/ruby
# $Id: tpops-useradd,v 1.2 2001/05/07 04:14:37 tommy Exp $

require 'mysql'

Dir = $0.sub(/[^\/]*$/, '')
load Dir+'/tpops.conf'

if ARGV.size != 3 then
  $stderr.puts "usage: tpops-useradd login passwd mail_address"
  exit 1
end

login, passwd, mail = ARGV

my = Mysql::new(MySQL_Server, MySQL_User, MySQL_Pass, MySQL_DB)
my.query("insert into user (login,passwd,mail) values ('#{my.quote login}','#{my.quote passwd}','#{my.quote mail}')")
my.close
