#!/usr/local/bin/ruby
# $Id: tpops-store,v 1.4 2001/05/19 08:53:05 tommy Exp $

require 'mysql'

EX_OK = 0
EX_USAGE = 64
EX_NOUSER = 67
EX_TEMPFAIL = 75

Dir = $0.sub(/[^\/]*$/, '')
load Dir+'tpops.conf'

if ARGV.size < 1 then
  $stderr.puts "usage: tpops-store mail_address [files...]"
  exit EX_USAGE
end

def store(msg)
  i = msg.index(/\r?\n\r?\n/)
  if i then
    i += 4
    h = msg[0, i]
    b = msg[i..-1]
  else
    h = msg
    b = ''
  end
  @my.query("insert into msg (uid,header,body,timestamp) values (#{@uid},'#{@my.quote h}','#{@my.quote b}',now())")
end

begin 

  mail = ARGV.shift

  @my = Mysql::new(MySQL_Server, MySQL_User, MySQL_Pass, MySQL_DB)
  res = @my.query("select uid from user where mail='#{@my.quote mail}'")
  if res.num_rows == 0 then
    puts "#{mail}: unknown user"
    exit EX_NOUSER
  end
  @uid = res.fetch_row[0].to_i

  if ARGV.size == 0 then
    store $stdin.read
  else
    ARGV.each do |fname|
      File::open(fname) do |f|
	store f.read
      end
    end
  end

  @my.close

rescue
  bt = $!.backtrace
  $stderr.puts "#{bt.shift}: #{$!.error} (#{$!.type})"
  bt.each do |l|
    $stderr.puts "\tfrom #{l}"
  end
  exit EX_TEMPFAIL
end

exit EX_OK
